# Generated by Django 5.2 on 2025-04-18 09:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=core.utils.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=core.utils.generate_slug, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan', models.ImageField(upload_to=core.utils.image_upload_path)),
                ('interior_photo', models.ImageField(upload_to=core.utils.image_upload_path)),
                ('door_height', models.FloatField()),
                ('ceiling_height', models.FloatField()),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to=core.utils.image_upload_path)),
                ('products', models.ManyToManyField(blank=True, to='core.product')),
            ],
        ),
    ]
