# Generated by Django 5.2 on 2025-05-03 18:16

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Toilet', 'Toilet'), ('Sink', 'Sink'), ('Bath', 'Bath'), ('Shower', 'Shower'), ('Faucet sink', 'Faucet Sink'), ('Faucet bidet', 'Faucet Bidet'), ('Faucet shower', 'Faucet Shower'), ('Bidet', 'Bidet'), ('Urinal', 'Urinal'), ('Accesory', 'Accesory'), ('Drain', 'Drain'), ('Tile', 'Tile')], max_length=50, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=250, null=True)),
                ('stock_code', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('producing_country', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=core.utils.generate_slug, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan', models.ImageField(upload_to=core.utils.image_upload_path)),
                ('interior_photo', models.ImageField(upload_to=core.utils.image_upload_path)),
                ('door_height', models.FloatField()),
                ('ceiling_height', models.FloatField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('wall_area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to=core.utils.image_upload_path)),
                ('products', models.ManyToManyField(blank=True, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store'),
        ),
    ]
