# Generated by Django 5.2 on 2025-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='media/static')),
            ],
        ),
        migrations.AddField(
            model_name='designrequest',
            name='area',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='perimeter',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='wall_area',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
