# Generated by Django 5.2 on 2025-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_designrequest_area_designrequest_perimeter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='perimeter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='wall_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
