# Generated by Django 5.2 on 2025-05-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_usd',
            new_name='price',
        ),
    ]
